### ISSUE TITLE
Weird parsing error

### ISSUE THREAD

**Issue by sksamuel** [uniVocity/univocity-parsers#194] opened 2017-10-04 21:04 UTC
Sometimes, say every 5 attempts, I get an error where only part of the row is parsed.
It manifests itself by only returning the first character of the row as the "complete row".
I've tried input streams, byte arrays etc and always the same thing.
Version 2.5.6

I know this is a rubbish bug report but I don't know what else to say, other than the error is _always_ that the row is parsed as a single character.

**Comment by jbax** [comment] 2017-10-05 04:02
Thanks for reporting! It sounds like a duplicate of https://github.com/uniVocity/univocity-parsers/issues/186 as something like that was the root cause of the issue.

Can you share the code you are using to test this using byte arrays?

**Comment by sksamuel** [comment] 2017-10-05 07:07
Yeah it does seem similar to that. The code I use is part of a larger code base.

The csv code is here:
https://github.com/51zero/eel-sdk/blob/master/eel-core/src/main/scala/io/eels/component/csv/CsvPublisher.scala#L25-L52

Which then shows up in the csv tests here:
https://github.com/51zero/eel-sdk/blob/master/eel-core/src/test/scala/io/eels/component/csv/CsvSourceTest.scala

And also here:
https://github.com/51zero/eel-sdk/blob/master/eel-core/src/test/scala/io/eels/datastream/DataStreamTest.scala#L14-L16

I've played about locally with extra logging to print out the record before my codebase fails the tests because the rows are malformed.

I think it might be concurrency related because when I use the debugger I cannot re-produce the error, indicating that the slowness of the debugger is giving the parsers extra time to do something.

A logging example...

In this one, the values array contains only a single quote mark, but should contain a row.
```
java.lang.IllegalArgumentException: requirement failed: Row should have a value for each field (11 fields=first_name,last_name,company_name,address,city,county,postal,phone1,phone2,email,web, 1 values=")
```
This then happened for 4 out of the 47 tests.

**Comment by sksamuel** [comment] 2017-10-05 07:34
I've written this,

```
class CsvTest extends FunSuite with Matchers with Logging {

  test("concurrent loading") {
    val executor = Executors.newFixedThreadPool(20)
    for (k <- 1 to 1000) {
      executor.execute(new Runnable {
        override def run() = {
          try {
            val data = IOUtils.toByteArray(getClass.getResourceAsStream("/uk-500.csv"))
            val source = CsvSource(data)
            require(source.toDataStream.collect.size == 500)
          } catch {
            case e: Exception =>
              logger.error("oops", e)
          }
        }
      })
    }
    executor.shutdown()
    executor.awaitTermination(1, TimeUnit.DAYS)
  }
}
```

And I get lots of,

```
com.univocity.parsers.common.TextParsingException: java.io.IOException - Stream closed
Parser Configuration: CsvParserSettings:
	Auto configuration enabled=true
	Autodetect column delimiter=false
	Autodetect quotes=false
	Column reordering enabled=true
	Empty value=null
	Escape unquoted values=false
	Header extraction enabled=false
	Headers=null
	Ignore leading whitespaces=true
	Ignore trailing whitespaces=true
	Input buffer size=1048576
	Input reading on separate thread=true
	Keep escape sequences=false
	Keep quotes=false
	Length of content displayed on error=-1
	Line separator detection enabled=true
	Maximum number of characters per column=4096
	Maximum number of columns=512
	Normalize escaped line separators=true
	Null value=null
	Number of records to read=all
	Processor=none
	Restricting data in exceptions=false
	RowProcessor error handler=null
	Selected fields=none
	Skip bits as whitespace=true
	Skip empty lines=true
	Unescaped quote handling=nullFormat configuration:
	CsvFormat:
		Comment character=#
		Field delimiter=,
		Line separator (normalized)=\n
		Line separator sequence=\n
		Quote character="
		Quote escape character="
		Quote escape escape character=null
Internal state when error was thrown: line=1, column=0, record=1, charIndex=107, headers=[first_name, last_name, company_name, address, city, county, postal, phone1, phone2, email, web]
	at com.univocity.parsers.common.AbstractParser.handleException(AbstractParser.java:364) ~[univocity-parsers-2.5.6.jar:2.5.6]
	at com.univocity.parsers.common.AbstractParser.stopParsing(AbstractParser.java:427) ~[univocity-parsers-2.5.6.jar:2.5.6]
	at io.eels.component.csv.CsvSource$$anonfun$schema$1.apply(CsvSource.scala:87) ~[classes/:?]
	at io.eels.component.csv.CsvSource$$anonfun$schema$1.apply(CsvSource.scala:63) ~[classes/:?]
	at scala.Option.getOrElse(Option.scala:121) ~[scala-library-2.11.11.jar:?]
	at io.eels.component.csv.CsvSource.schema(CsvSource.scala:63) ~[classes/:?]
	at io.eels.component.csv.CsvSource.parts(CsvSource.scala:93) ~[classes/:?]
	at io.eels.datastream.DataStreamSource.subscribe(DataStreamSource.scala:17) ~[classes/:?]
	at io.eels.datastream.DataStream$class.collect(DataStream.scala:860) ~[classes/:?]
	at io.eels.datastream.DataStreamSource.collect(DataStreamSource.scala:11) ~[classes/:?]
	at io.eels.component.csv.CsvTest$$anonfun$1$$anonfun$apply$mcZ$sp$1$$anon$1.run(CsvTest.scala:19) [test-classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.io.IOException: Stream closed
	at sun.nio.cs.StreamDecoder.ensureOpen(StreamDecoder.java:46) ~[?:1.8.0_45]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:148) ~[?:1.8.0_45]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.8.0_45]
	at com.univocity.parsers.common.input.concurrent.CharBucket.fill(CharBucket.java:70) ~[univocity-parsers-2.5.6.jar:2.5.6]
	at com.univocity.parsers.common.input.concurrent.ConcurrentCharLoader.run(ConcurrentCharLoader.java:84) ~[univocity-parsers-2.5.6.jar:2.5.6]
	... 1 more
```

**Comment by jbax** [comment] 2017-10-05 09:19
Thanks, I cloned your repo to get your `uk-500.csv` file and I am able consistently get errors when parsing with it in [this test case](https://github.com/uniVocity/univocity-parsers/commit/87d9a255ae82083e1a93903d3ad7007b9711992b)

Variations of this issue are happening since version 2.5.0 which introduced support for handling BOM markers. I am investigating and will hopefully get this nailed soon, but essentially it will only happen when `setReadInputOnSeparateThread = true` AND you don't provide an encoding for your InputStream/File. This triggers the [BomInput](https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/common/input/BomInput.java) which will read the first few bytes in order to detect the file encoding if possible.

In the meantime, the workaround to have things working consistently is to either:
- provide the encoding explicitly
- set `setReadInputOnSeparateThread = false`

**Comment by sksamuel** [comment] 2017-10-05 09:20
Fast work! I'll use the workaround now, thanks.

**Comment by jbax** [comment] 2017-10-05 14:44
Fixed and released a 2.5.7-SNAPSHOT build that hopefully puts an end to this. Thank you for reporting the issue and for using our parsers!

**Closed by jbax** 2017-10-05 14:44 UTC
Labels: bug

**Comment by jbax** [comment] 2017-10-09 08:29
Just letting you know that version `2.5.7` has been released with this fix. Cheers!

**Comment by sksamuel** [comment] 2017-10-13 19:29
Excellent.
