### ISSUE TITLE
Comment-Setting ignored - Race Condition?

### ISSUE THREAD

**Issue by blackfoxoh** [uniVocity/univocity-parsers#187] opened 2017-09-08 09:24 UTC
Hi,
we have a testcase which failed once now (but worked fine before and now again without changing anything).

There is a ProcessingBean containing 
```
   @Parsed(index = 1)
   private int orderNr;
   
   @Parsed(index = 3)
   private String pkNr;
   
   @Parsed(index = 6)
   private int status;
```
And this is used as following:
```
      BeanListProcessor<ProcessingBean> rowProcessor = new BeanListProcessor<ProcessingBean>(ProcessingBean.class);

      CsvParserSettings parserSettings = new CsvParserSettings();
      parserSettings.setProcessor(rowProcessor);
      parserSettings.setHeaderExtractionEnabled(false);
      parserSettings.setLineSeparatorDetectionEnabled(true);
      parserSettings.getFormat().setComment('#');
      parserSettings.getFormat().setDelimiter(';');
      CsvParser parser = new CsvParser(parserSettings);

      parser.parse(file);
      List<ProcessingBean> listProcessingBean = rowProcessor.getBeans();
```

The file to be imported starts as following:
```
# FILE;N00;CUST;20199119;132448;668221;
# VERSION;1.2;
# DEF;CR:CRDATA02;ODEPOT;ORDERNR;RDEPOT;PKNR;NEUDAT;PICKUPDATE;STATUS;WEIGHT;SERVICE;CUSTOM;SCANTYPE;ZCODE;CUSTREF;CONFIRM;CANCELUSER;;
0999;960999;0699;06299995899999;20160199;;1;0.000000;;;18;072;03212999/8999748;0;;
```

When the import failed we got a NumberFormatException and the following errormessage:
class com.univocity.parsers.common.DataProcessingException - Error converting value 'N00' using conversion com.univocity.parsers.conversions.IntegerConversion
Internal state when error was thrown: line=1, column=0, record=1, charIndex=39, headers=[FILE, N00, CUST, 20199119, 132448, 668221, null], row=[20199119, N00, null], value=N00, columnName=N00, columnIndex=1

This seems to me as the parserSettings were not used??? (Headerextraction disabled, Comment #) At least the first row marked as comment was read as a regular line. Of course, parsing this results in the NFE when trying to convert to the ProcessingBean...
As there are no more logs I don't know how to narrow down the problem - and as said, the error occured just once so far (same code, same input, executed regularly)...

**Comment by jbax** [comment] 2017-09-08 13:13
This is a regression introduced in version 2.5.0 onward, but fixed a couple
of days ago. Can you try with version 2.5.5-SNAPSHOT?

The first character may be lost when you provide a file or inputstream
without the character encoding.

As a workaround you can explicitly provide the encoding, or use a
FileReader, or disable reading input from a separate thread.


On 8 Sep. 2017 6:54 pm, "blackfoxoh" <notifications@github.com> wrote:

Hi,
we have a testcase which failed once now (but worked fine before and now
again without changing anything).

There is a ProcessingBean containing
` @parsed <https://github.com/parsed>(index = 1)
private int orderNr;

@parsed <https://github.com/parsed>(index = 3)
private String pkNr;

@parsed <https://github.com/parsed>(index = 6)
private int status;
`

`
BeanListProcessor rowProcessor = new BeanListProcessor(
ProcessingBean.class);

  CsvParserSettings parserSettings = new CsvParserSettings();
  parserSettings.setProcessor(rowProcessor);
  parserSettings.setHeaderExtractionEnabled(false);
  parserSettings.setLineSeparatorDetectionEnabled(true);
  parserSettings.getFormat().setComment('#');
  parserSettings.getFormat().setDelimiter(';');
  CsvParser parser = new CsvParser(parserSettings);

  parser.parse(file);
  List<ProcessingBean> listProcessingBean = rowProcessor.getBeans();

`

The file to be imported starts as following:
`
FILE;N00;CUST;20199119;132448 <13%2024%2048>;668221; VERSION;1.2;
DEF;CR:CRDATA02;ODEPOT;ORDERNR;RDEPOT;PKNR;NEUDAT;PICKUPDATE;STATUS;WEIGHT;
SERVICE;CUSTOM;SCANTYPE;ZCODE;CUSTREF;CONFIRM;CANCELUSER;;

0999;960999;0699;06299995899999;20160199;;1;0.000000;;;18;072;03212999/
8999748;0;;
`

When the import failed we got a NumberFormatException and the following
errormessage:
class com.univocity.parsers.common.DataProcessingException - Error
converting value 'N00' using conversion com.univocity.parsers.
conversions.IntegerConversion
Internal state when error was thrown: line=1, column=0, record=1,
charIndex=39, headers=[FILE, N00, CUST, 20199119, 132448 <13%2024%2048>,
668221, null], row=[20199119, N00, null], value=N00, columnName=N00,
columnIndex=1

This seems to me as the parserSettings were not used??? (Headerextraction
disabled, Comment #) At least the first row marked as comment was read as a
regular line. Of course, parsing this results in the NFE when trying to
convert to the ProcessingBean...
As there are no more logs I don't know how to narrow down the problem - and
as said, the error occured just once so far (same code, same input,
executed regularly)...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/uniVocity/univocity-parsers/issues/187>, or mute the
thread

**Comment by jbax** [comment] 2017-09-08 21:52
Version 2.5.5 released. Use that version and the issue will be gone. Thank you for using our parsers!

**Closed by jbax** 2017-09-08 21:52 UTC

**Comment by jbax** [comment] 2017-09-08 22:01
Marking as duplicate of https://github.com/uniVocity/univocity-parsers/issues/186

**Comment by blackfoxoh** [comment] 2017-09-11 08:03
Hi jbax
thank you for the quick response and releasing the bugfix.
