### ISSUE TITLE
Inconsistent result of parseLine on empty set of selected indexes

### ISSUE THREAD

**Issue by MaxGekk** [uniVocity/univocity-parsers#250] opened 2018-06-29 20:07 UTC
I faced to the issue when I was reviewing the Spark's PR: https://github.com/apache/spark/pull/21631

The `parseLine` method returns different values for similar input strings in the case if empty set of indexes is passed to `selectIndexes()` like:

```scala
val tokenIndexArr = Seq.empty[java.lang.Integer]
parserSetting.selectIndexes(tokenIndexArr: _*)
val tokenizer = new CsvParser(parserSetting)
```

For example:

```
parseLine("0") -> []
parseLine("1") -> null
parseLine("2") -> null
parseLine("3") -> null
```

What would I expect is the same output for all calls - either `null` or `empty array`. Also `empty array` would be more preferable than `null`. The returned `null` was the actual root cause of `NullPointerException` in Spark fixed by the PR: https://github.com/apache/spark/pull/21631

Here is the code with settings extracted from CSV datasource of Spark which demonstrates the described behavior: https://github.com/MaxGekk/univocity_tests

**Comment by jbax** [comment] 2018-06-30 16:44
Thank you for reporting the bug, I'm working to have it fixed ASAP

**Comment by jbax** [comment] 2018-06-30 17:10
Fixed and released a 2.6.5-SNAPSHOT build you can use for testing. Thanks again

**Comment by MaxGekk** [comment] 2018-06-30 17:52
Thank you @jbax

**Comment by jbax** [comment] 2018-07-10 02:33
@MaxGekk Version 2.7.0 released with this fix. Thank you!

**Comment by MaxGekk** [comment] 2018-07-12 13:16
@jbax I bumped version to 2.7.1 in my test app https://github.com/MaxGekk/univocity_tests , and see the same returned values of `parseLine`:
```
"0" -> []
"1" -> null
"2" -> null
"3" -> null
"4" -> null
```

**Comment by jbax** [comment] 2018-07-12 13:53
You are correct! I just reviewed my test case and it was printing to the output instead of using asserts! No wonder the test passed. I made it work once but apparently introduced some regression as well. Checking

**Closed** 2018-07-12 14:44 UTC
Labels: bug

**Comment by jbax** [comment] 2018-07-12 14:45
Done, the latest 2.7.2-SNAPSHOT build should have this bug fixed. Thank you!

**Comment by MaxGekk** [comment] 2018-07-27 14:13
@jbax I have bumped version in Spark up to 2.7.2: https://github.com/apache/spark/pull/21892 . The difference in performance between 2.6.3 and 2.7.2 is not significant except a case when the set of selected indexes is empty. We did some changes recently regarding to handling of empty schema. So, if the schema is empty (the set of selected indexes is empty), we do not call parser at all. I have reverted the changes because now the parser can return "valid" empty array and got performance penalty up to 3.8 times. Just wondering is it possible to optimize this particular case?

**Comment by jbax** [comment] 2018-07-27 21:43
Hi @MaxGekk, I had a look at your benchmark results and the performance hit seems to be coming from instantiating a new empty String[] for every record that is parsed. Previously you were getting nulls so that's why latest version got slower when dealing with this particular case. I've made a minor adjustment to return a static `EMPTY_STRING_ARRAY` instead of generating new instances. Can you try running your benchmark again with the latest 2.7.3-SNAPSHOT build I just released and let me know if things improved?
