### ISSUE TITLE
Parsing of quoted text with quotes inside

### ISSUE THREAD

**Issue by JoyW3000** [uniVocity/univocity-parsers#271] opened 2018-08-13 18:07 UTC
I tried different parser settings for unescaped quote handling (UnescapedQuoteHandling.STOP_AT_DELIMITER or UnescapedQuoteHandling.STOP_AT_CLOSING_QUOTE), the outcome is still wrong.
`CsvParserSettings parserSettings = new CsvParserSettings();
        parserSettings.setLineSeparatorDetectionEnabled(true);
        parserSettings.setHeaderExtractionEnabled(true);
        parserSettings.setDelimiterDetectionEnabled(true);
        parserSettings.setQuoteDetectionEnabled(true);
        parserSettings.setUnescapedQuoteHandling(UnescapedQuoteHandling.STOP_AT_DELIMITER);
        parserSettings.setReadInputOnSeparateThread(true);
        parserSettings.setNumberOfRowsToSkip(rowsToSkip);
        parserSettings.trimValues(true);
        ColumnProcessor rowProcessor = new ColumnProcessor();
        parserSettings.setProcessor(rowProcessor);
        CsvParser lineParser = new CsvParser(parserSettings);`

Here's the input csv file for parsing:
` "name"|"description"|"digit"|"other"\n
"test one"|"test description with ""|"1"|"other one"\n
"test two"|"test description without a quote"|"2"|"other two"\n`

Here's the output after parsing:
`["name", "description", "digit", "other"]\n
["test one", "test description with "|"1", "other one"]\n
["test two", "test description without a quote", "2", "other two"]\n`

As you can see,  "test description with "|"1" is grouped as one element

**Comment by jbax** [comment] 2018-08-14 07:25
Duplicate of #259.

Basically this setting will make the parser stop at the delimiter AFTER the unescaped quote is found. Your value is properly escaped until it reaches the `1` character instead of another `"`  just after  collecting the `|` character after `test description with ""|"`

It doesn't go back and break the value if has in the first occurernce of `|`. As it was all fine until it went through `test description with ""|`, it will stop when it finds the next `|`.

Hope this makes sense.

**Closed by jbax** 2018-08-14 07:25 UTC

**Comment by jbax** [comment] 2018-10-11 10:59
Fixed and released a 2.8.0-SNAPSHOT build with this enhancement. 

If you want to test this, follow these instructions to get the snapshot: https://www.univocity.com/pages/univocity_parsers_download#snapshot-releases

Thank you for using our parsers!

**Comment by JoyW3000** [comment] 2018-10-21 13:49
I tried UnescapedQuoteHandling.STOP_AT_DELIMITER, BACK_TO_DELIMITER and STOP_AT_CLOSING_QUOTE on 2.8.0-SNAPSHOT.  I still got the same result as before.  It still grouped the 2nd line as ["test one", "test description with "|"1", "other one"].  Can you please let me know if I missed something?

**Comment by jbax** [comment] 2018-10-21 22:04
Thanks for letting me know! I just fixed the issue - in my tests I used

`parserSettings.getFormat().setDelimiter('|');`

instead of what you did:

`parserSettings.setDelimiterDetectionEnabled(true);`

The auto-detected delimiter was not being updated properly and that's why it failed again for you. This should be fixed now and if you get the latest 2.8.0-SNAPSHOT build it should work for you.

Thanks again!

**Comment by JoyW3000** [comment] 2018-10-22 16:03
I think there's still some error in BACK_TO_DELIMITER. 
I got
["test one", "test description with ", 1", "other one"]
["test two", "test description without a quote", "2", "other two"]

In the first line, A quotation sign is missing in "test description with "", and the opening quotation is missing in 1".  

Thank you for trying to fix this in a SNAPSHOT build.  Delimiter auto-detection is needed for my projects.  Is it going to be fixed in the next version release?

**Comment by jbax** [comment] 2018-10-23 02:58
I'm getting the correct results with this code:

```
		String input = "\"name\"|\"description\"|\"digit\"|\"other\"\n \"test one\"|\"test description with \"\"|\"1\"|\"other one\"\n \"test two\"|\"test description without a quote\"|\"2\"|\"other two\"\n";

		CsvParserSettings parserSettings = new CsvParserSettings();
		parserSettings.setUnescapedQuoteHandling(UnescapedQuoteHandling.BACK_TO_DELIMITER);

		parserSettings.setLineSeparatorDetectionEnabled(true);
		parserSettings.setHeaderExtractionEnabled(true);
		parserSettings.setDelimiterDetectionEnabled(true);
		parserSettings.setQuoteDetectionEnabled(true);

		CsvParser parser = new CsvParser(parserSettings);
		List<String[]> rows = parser.parseAll(new StringReader(input));
		assertEquals(rows.size(), 2);

		String[] row;
		row = rows.get(0);
		assertEquals(row.length, 4);
		assertEquals(row[0], "test one");
		assertEquals(row[1], "test description with \"");
		assertEquals(row[2], "1");
		assertEquals(row[3], "other one");

		row = rows.get(1);
		assertEquals(row.length, 4);
		assertEquals(row[0], "test two");
		assertEquals(row[1], "test description without a quote");
		assertEquals(row[2], "2");
		assertEquals(row[3], "other two");
```

Can you provide the code you are using on your test so I can reproduce this?

The delimiter auto-detection is fixed on the latest SNAPSHOT build already and will be fixed in the next version release.

Thanks again

**Comment by JoyW3000** [comment] 2018-10-31 17:54
The error was caused by parserSettings.setKeepQuotes(true).  Otherwise the result's correct.  Is this fix going to be added to the next release with the delimiter auto detection capability?  
Thank you.

**Comment by jbax** [comment] 2018-11-01 02:10
Thanks for the update. I've fixed the issue with the `keepQuotes` setting on the latest SNAPSHOT build. Should work fine now.

**Comment by JoyW3000** [comment] 2018-11-01 10:54
It's fixed now.  Thank you!

**Comment by LucasES** [comment] 2019-03-25 17:56
I have a similar problem. 
I tried to parse my CSV into bean, but when the line start with quotation mark the parser parse in a single attribute.
Example csv:

> Application,,,Order Id,,,Job Name,,Start Time,,,End Time,,,,,Average Runtime,,,Elapsed Runtime,,,Average Start Time,,From Time,,,To Time,,,Cyclic,,,Deleted,,Max Rerun,,,Rerun Counter,,,Odate,,,State,,,Status
NMW_APP,,,5y0jr,,,NMWLPD042,,20181204152405,,,,,,,,000550,,,0,,,072405,,0710,,,0610,,,True,,,0,,24,,,1,,,181204,,,Wait Execution Run (2),,,Executing
"HMR_APP,,,5y1cw,,,HMRWPD001,,20181204153002,,,,,,,,002102,,,""126,200"",,,064905,,0700,,,0659,,,True,,,0,,0,,,19,,,181204,,,Run (20),,,Executing"

CsvParser:
` CsvParserSettings parserSettings = new CsvParserSettings();
        parserSettings.setLineSeparatorDetectionEnabled(true);
        parserSettings.setHeaderExtractionEnabled(true);
        parserSettings.setSkipEmptyLines(true);
        parserSettings.setUnescapedQuoteHandling(UnescapedQuoteHandling.BACK_TO_DELIMITER);`

I need skip the quotes at beginning and end of line. can someone help me?
Thanks

**Comment by jbax** [comment] 2019-03-26 00:10
@LucasES your input does not have any unescaped quote and the parser is generating very long line because the CSV is 100% valid, well-formed and correct (for the parser, not for you). 

If you can't get your file fixed, the only solution I can see is to ignore quotes altogether with:

```
parserSettings.getFormat().setQuote('\uffff');
```

The problem now is that your values will have quotes, so you will see values such as `"HMR_APP` and `Executing"`. You need to fix that by removing the quotes yourself (use `@Replace("\\\"", "")` in the attributes of your bean that might have quotes. 

Hope this helps
