### ISSUE TITLE
Null value set for missing fields

### ISSUE THREAD

**Issue by raphkr** [uniVocity/univocity-parsers#116] opened 2016-09-14 18:17 UTC
I have fields in my code which are missing from the CSV i am trying to parse. In my parser settings I have set the default null value to be an empty string. However for the missing fields, the value being set is null.

I would like to know if this is the desired behaviour or am i doing something wrong??

**Comment by jbax** [comment] 2016-09-15 02:18
Can you please provide some sample code that reproduces this issue you're having?
Thank you!

**Comment by raphkr** [comment] 2016-09-15 06:29
//TSV parser settings defined
TsvParserSettings parserSettings = new TsvParserSettings();
parserSettings.setNullValue("");
...
...
TsvParser parser = new TsvParser(parserSettings);

//Model class for CSV
@Parsed(field="A")
private String a;
@Parsed(field="B")
private String b;
@Parsed(field="C")
private String c;

My CSV has feilds:
A\tB

So here is my scenario:
If I leave a column value (eg. A) empty then an empty string is set for that as the default null value. However if the field as defined in the model is not present in the CSV(i.e C), then the parser seems to completely ignore that and does not set the default null value as an empty string.

Let me know if you need anything more from me.

Thanks for the prompt reply!!! 👍

**Comment by jbax** [comment] 2016-09-15 06:50
Thank you. The parser behaves like this by design": if nothing is parsed then you will get `null`. If you actually parse a column, but the value is `null`, then you get the `nullValue`.

Having said that, you can set a value for `defaultNullRead` in the annotations:

```

@Parsed(field="A", defaultNullRead="")
private String a;
@Parsed(field="B", defaultNullRead="N/A")
private String b;
@Parsed(field="C", defaultNullRead="etc")
private String c;

```

Hope this helps.

**Comment by raphkr** [comment] 2016-09-15 06:57
Thanks Alot.

**Comment by raphkr** [comment] 2016-09-16 11:15
Hey. I tried using the default null value parameter, however that too didnt seem to do the job.

**Comment by jbax** [comment] 2016-09-16 14:34
To be fixed with version 2.2.2 (planned to be released on Monday)

**Comment by jbax** [comment] 2016-09-19 09:42
Fixed. Version 2.2.2 was just released and includes this adjustment.
Thank you for using our parsers!

**Closed by jbax** 2016-09-19 09:42 UTC
Labels: bug

**Comment by raphkr** [comment] 2016-09-21 06:41
Thanks.

**Comment by binhvinhmai** [comment] 2017-07-14 14:38
Hey the issue still exists in Univocity where if the column doesn't exist, the attribute in the POJO is still set to null - defaultNullRead="" doesn't seem to be working, and so if nothing is parsed, the value is left as a null value. Has this been corrected? Sorry to bring up an old issue but I'm still facing this issue that raphkr was facing in Univocity-Parsers 2.4.1.

**Comment by jbax** [comment] 2017-07-14 15:32
@binhvinhmai  the unit test I originally created for this issue doesn't reveal any issues. Do you mind sharing the code you are using (or some simplified version of it) that reproduces the issue you are having?
