### ISSUE TITLE
Issue with detected delimiter

### ISSUE THREAD

**Issue by gowravshekar** [uniVocity/univocity-parsers#216] opened 2017-11-27 07:23 UTC
I'm trying to detect the delimiter of CSV/TSV files.

Sample CSV file
https://archive.ics.uci.edu/ml/machine-learning-databases/statlog/german/german.data

The detected delimiter is `comma(,)` but the actual one is `space( )`.

You can see my code below.

```scala
// Enable detection of delimiter, line separator and text qualifier.
val parserSettings = new CsvParserSettings
parserSettings.setDelimiterDetectionEnabled(true)
parserSettings.setLineSeparatorDetectionEnabled(true)
parserSettings.setQuoteDetectionEnabled(true)

// Begin parsing and read first non empty line from file.
val parser = new CsvParser(parserSettings)
parser.beginParsing(input)
parser.parseNext()

// Obtain the attributes from row parsing.
val format = parser.getDetectedFormat

// Stop parsing the file.
parser.stopParsing()

// Close the input stream.
input.close()
```

**Comment by jbax** [comment] 2017-11-27 13:10
That's because currently the detection process simply doesn't account for white spaces (except the tab character) as special characters that could be used as the separator. 

I'll mark this as a duplicate of #214 as allowing the user to provide a set of possible delimiters should take care of this.

**Closed by jbax** 2017-11-27 13:10 UTC

**Comment by gowravshekar** [comment] 2017-11-27 17:18
Thanks for the clarification. One of my recommendation is when the detection is enabled, throw an exception or return an error message instead of sending the default one. By doing this, the developer is aware that the delimiter isn't detected. I tried the same dataset with [papaparse](http://papaparse.com/demo) CSV parser. They provide an error message. This is applicable for all detections - Delimiter, Line separator, quote.

**Comment by jbax** [comment] 2017-11-28 00:33
Thanks for the suggestion. We can't start throwing exceptions because it will break backward compatibility. The exception doesn't make a lot of sense because if the heuristic picks up a symbol in a very odd input - and it's not the correct one - you will have errors parsing anyway.
