### ISSUE TITLE
How to tune sample size but still leverage univocity CsvParser

### ISSUE THREAD

**Issue by fluxquantum** [uniVocity/univocity-parsers#407] opened 2020-07-29 13:53 UTC
Hello, appreciate the work that came into building this library. 

For some of our files we have been getting inconsistent parsing results for a given records in the same file, we suspect that the delimiters being detected may vary depending on the chunks of the file being processed. 

We believe that tuning some of the parser settings will allow us to get insight on how to achieve more accurate results in certain cases.

I see that you have already made the InputAnalysisProcess and CsvFormatDetector public to allow for some customized implementation but the max sample size used when initializing the CsvParser is 20.

I was wondering if you may suggest a way we could also tune the max samples settings attached to the CsvParser or any alternative approach.

Thank you for your time.

**Comment by jbax** [comment] 2020-07-29 14:04
You can provide a pre-determined set of allowed separators. Also note that
it won't work if the input has unescaped quotes.

If you think increasing the sample size will help, try recompiling the code
with a larger size to test your theory. I suspect it won't help.

Format detection is not deterministic and the heuristic implemented in the
parser does what it can but there is no guarantee it will work for every
input.

You can also try the latest 2.8.5-Snapshot.

Hope this helps

**Comment by fluxquantum** [comment] 2020-07-29 14:27
Thanks for providing those details and your thoughts. We are passing a list of possible delimiters which has been helpful.

May you elaborate on how come you think increasing the sample size won't make an appreciable difference?

How we can recompile the code with a different sample size? It doesn't look like we can update it unless we are able to override the CsvParser or write a custom parser in conjunction with the 2.8.5 snapshot.

Thanks for the help.

**Comment by jbax** [comment] 2020-07-29 15:16
I don't think it will because it assumes the input has a regular layout
with rows containing more or less the same number of columns. It wont help
if that's not your case, or the input has unescaped quotes, or multiple
potential delimiters appear in each row consistently in the same numbers.

Maybe I'm wrong so try and clone the repository, change the sample size,
build it with `mvn clean install -DskipTests=true` and see if a larger
sample size makes any difference.

**Comment by jbax** [comment] 2020-07-31 11:46
closing as duplicate of #408

**Closed by jbax** 2020-07-31 11:46 UTC
