### ISSUE TITLE
CsvParser doesn't reload headers

### ISSUE THREAD

**Issue by Luke791** [uniVocity/univocity-parsers#319] opened 2019-04-01 11:01 UTC
CsvParser from version 2.8.0 doesn't have any more the method reloadHeaders and it doesn't realod headers when it begins parsing another csv.

This is my code:
```
CsvParserSettings settings = new CsvParserSettings();
settings.detectFormatAutomatically();
settings.setHeaderExtractionEnabled(true);
settings.setAutoClosingEnabled(false);
CsvParser parser = new CsvParser(settings);

parser.beginParsing(inputStreamOnFile1, "UTF-8");
Record record = parser.parseNextRecord();
RecordMetaData metadata = record.getMetaData();
System.out.println(metadata.headers()); //headers of File1
parser.stopParsing();

parser.beginParsing(inputStreamOnFile2, "UTF-8");
Record record = parser.parseNextRecord();
RecordMetaData metadata = record.getMetaData();
System.out.println(metadata.headers()); // STILL HEADERS OF FILE1!!!
parser.stopParsing();
```

**Comment by jbax** [comment] 2019-04-01 13:29
That was fixed on version 2.8.1. Duplicate of #309

**Closed** 2019-04-01 21:16 UTC
Labels: duplicate
