### ISSUE TITLE
CSV parser breaks with incorrect quoting.

### ISSUE THREAD

**Issue by garretwilson** [uniVocity/univocity-parsers#297] opened 2018-12-21 18:13 UTC
We're parsing some data from a state government department, and of course the formatting is atrocious, but perhaps no more than is typical from data dumps in the wild. The CSV file starts with a header, and none of the values are quoted:

```
DocNum,LastName,FirstName,MiddleInit,Suffix,Race,Gender,…
```

Than after over a thousand lines we get a row that has a lone double quote for `MiddleInit`:

```
123456,Smith,John,",,White,Male,…
```

Unfortunately Univocity hasn't picked up on the fact (after more than 1,000 lines) that this file doesn't really use quoting (even though it should; some cells contain commas, but I digress). So it thinks the next 40 lines or so _are part of the same cell_!! But the worst part is that the parser simply crashes:

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 4096 out of bounds for length 4096
	at com.univocity.parsers.common.input.DefaultCharAppender.appendUntil(DefaultCharAppender.java:257)
	at com.univocity.parsers.csv.CsvParser.parseQuotedValue(CsvParser.java:335)
	at com.univocity.parsers.csv.CsvParser.parseRecord(CsvParser.java:166)
	at com.univocity.parsers.common.AbstractParser.parse(AbstractParser.java:123)
	... 14 more
```

I know we have bad input data, but again I'm sure it's typical of real-world data. And sure, maybe Univocity can't guess everything, but the one thing it can do is _not crash_. Even if it thought that this was a multiline cell, it shouldn't crash, and especially not with an index out of bounds exception. (And why is it crashing at index 4096? Does it not support cells longer than 4096 characters?)

So the highest priority here is to fix the logic bug that doesn't correctly check array indexes.

Secondly, from reading the documentation, I was thinking that the Univosity parser would be a little smarter about dealing with bad data. Here are just a few heuristics that would have tipped it off that this was _not_ a multiline cell:

* There had not been any double quote characters in the first 1,000 lines in the file.
* For this column, not a single other string value in over 1,000 had been _more than one character_. Does it seem reasonable that suddenly we would have a 40-line cell for that column?
* Just oddly enough, this supposedly quoted cell started with `,,`, which makes it seem that this was just a lone, out-of-place double quote.

OK, fine, maybe this level of reasoning is beyond Univocity's scope. But we at least need a parser setting that says, "consider a newline to end a cell, even a quoted cell", so that a random quote doesn't wipe out lines and lines of input, if we know in advance an input file is not using newlines inside cells (quoted or not).

**Comment by garretwilson** [comment] 2018-12-21 18:34
Note that this is a blocker bug. I'm dead in the water here. I can't find any setting that allows me to work around this. Even in the worst case, the parser should have simply ignored a certain number of lines (which would not have been good, but at least I could have continued parsing the other 280,000-some lines in the file).

And this is the first file I even tried to parse with Univocity, ever!

I guess I'll just have to write my own CSV parser. 😞

**Comment by garretwilson** [comment] 2018-12-21 18:45
It's probably best if I write my own parser, anyway. I need more flexibility over specifying up-front what to expect in some columns (so that the parser can compensate for bad formatting on a per-cell basis). Anyway, the idea behind your parser and consistent API is nice. Good luck! I hope this bug report helped.

**Comment by jbax** [comment] 2018-12-21 18:57
The array index error message thrown at you should be preceded by a message
saying that you must check your settings or your input. It should also
suggest you to set maxCharsPerColumn to -1, so there is no limit of
characters to accumulate before throwing the towel.

By default the parser fails fast to not let your server run out of memory
if someone gives your program a file that does not conform to the expected
format. It's not hard to generate a csv bomb with an open quote that is
never closed and makes the parser accumulate 8gb in characters.

If your file does not have quotations at all, set the quote character to
`\0` and it will split records at every comma.

The heuristics you suggest will cause trouble if that input is to be
considered valid. In the majority of cases (99.999%) the behavior of trying
to find a closing quote is the expected and correct thing to do.

I hope this gives you a better understandig on what the parser does and why
it does it.

Thank you for using our parsers!

**Comment by garretwilson** [comment] 2018-12-21 19:06
> The array index error message thrown at you should be preceded by a message…

In my opinion a parser should not die because of an `ArrayIndexOutOfBoundsException`. That indicates a programming error. If it encounters data it can't handle, it should fail gracefully by throwing some semantically appropriate exception, documented in the contract of its API. The same goes for `NullPointerException`.

> If your file does not have quotations at all, set the quote character to `\0` and it will split records at every comma.

How is that done? I had already looked in `CsvParserSettings` and didn't find a way to set the quote character. I looked in the online tutorial as well.

**Comment by jbax** [comment] 2018-12-21 19:21
parserSettings.getFormat().setQuote('\0'); sould do the trick.

The ArrayIndexOutOfBoundsException is the cause of the TextParsingException
that is thrown at you. You should never get an
ArrayIndexOutOfBoundsException . Don't look at the last exception in the
stack trace. Look at the first one. That error has been handled and the
parser goes  above and beyond to give you as much details as it can to let
you know the cause of the error.

We let the ArrayIndexOutOfBoundsException to be thrown internally for
performance reasons. A boundary check on every character to be accumulated
into a value would slow things down for no added benefit.

**Comment by jbax** [comment] 2018-12-21 19:30
Glad to assist.

**Closed** 2018-12-26 06:06 UTC
