### ISSUE TITLE
Keep record after failure

### ISSUE THREAD

**Issue by anibalcatheringer** [uniVocity/univocity-parsers#356] opened 2019-10-08 13:43 UTC
Hi,
I was using the version 2.7.6 until today when I finally decided to upgrade to latest (2.8.3) and my tests started failing. Problem is that when I'm parsing the CSV I don't want to lose any record and only the tests that contains these cases are failing.

This is my error handling code:

```
csvParserSettings.setProcessorErrorHandler(new RetryableErrorHandler<ParsingContext>() {
            @Override
            public void handleError(DataProcessingException error, Object[] inputRow, ParsingContext context) {
                keepRecord();
            }
        });
```
So the keepRecord is not doing its job anymore. I'm loosing the bean that has a problem

**Comment by anibalcatheringer** [comment] 2019-10-14 10:42
So I've collected more information, this is happening because the attribute type is `Date` and I'm trying to send a string like: `15,08,1983`
With the previous version of the library it works fine

**Comment by jbax** [comment] 2019-11-26 07:21
Thank you but I'm unable to reproduce the error. Calling keepRecord works for me and I built [this unit test](https://github.com/uniVocity/univocity-parsers/blob/4202c50c4a63c809d8bbbde4494ce94250b1d053/src/test/java/com/univocity/parsers/issues/github/Github_356.java) for this.

Let me know if the issue still exists. I assume your input string `15,08,1983` was not quoted but it should not make a difference. I'm closing this issue but please reopen with an updated test case based on the one I created if you can.

Thank you for using our parsers!

**Closed by jbax** 2019-11-26 07:21 UTC

**Comment by JithinKS97** [comment] 2020-11-05 11:09
Hello, I'm also facing this issue, it occurs only when two cells have wrong format values in a row. I guess in the unit test, only once the cell is wrong.

**Comment by jbax** [comment] 2020-11-05 13:25
Without a unit test that reproduces the error there's no way I can help
you.
