### ISSUE TITLE
Concurrency Issue in AnnotationHelper.java

### ISSUE THREAD

**Issue by richard-hulm** [uniVocity/univocity-parsers#207] opened 2017-11-06 16:39 UTC
It's hard to give precise steps to reproduce, but essentially we're doing concurrent conversions of different files, using a BeanListProcessor from the same entity.

There seems to be an issue with AnnotationHelper.findAnnotation in that, it stores a reference to the lastProcessedElement

On the next method call, it will do if(annotatedElement.equals(lastProcessedElement))
But it seems that it's possible for lastAnnotationFound to change in this time, causing the wrong annotation to be returned.

We've worked around this in our codebase with making the conversion process synchronized.

A quick-win would be to make the AnnoationHelper.findAnnotation method synchronized, but a more complete solution may be to change the internals of findAnnotation to use a thread-safe caching mechanism

I've reproduced this on version 2.3.1 and 2.5.8

**Comment by jbax** [comment] 2017-11-06 21:54
Thank you for reporting the issue. I think it's a duplicate of #146. That should have been fixed since version 2.4.1. 

Looking at the code, method `findAnnotation` is already synchronized (see https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/annotations/helpers/AnnotationHelper.java#L868)

The overloaded `findAnnotation` (https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/annotations/helpers/AnnotationHelper.java#L944) is only called from within the first method so there's no need to synchronize this one.

[This unit test](https://github.com/uniVocity/univocity-parsers/blob/master/src/test/java/com/univocity/parsers/issues/github/Github_146.java) will should force an error to happen if there's a concurrency issue there, but I got no errors with version 2.5.8 even after playing with the test to try and force an error.

Can you double-check that your test actually ran with version 2.5.8? Sometimes the IDE plays up and still uses the old stuff.

Thanks!

**Comment by jbax** [comment] 2017-11-09 01:10
Closing as it's a duplicate that has been resolved already

**Closed by jbax** 2017-11-09 01:10 UTC
