### ISSUE TITLE
Parsed CSV map contains carriage return in key if the last header is duplicated

### ISSUE THREAD

**Issue by samarthd** [uniVocity/univocity-parsers#349] opened 2019-08-21 22:13 UTC
Hi! Firstly, thanks for this great utility. 

I believe I have found a bug where the parsed CSV row map will have a carriage return `\r` in a key if the last header in a CSV file is duplicated.

I realize that there really shouldn't even be duplicate header names if I'm going to parse it into a map, but this does seem like a bug regardless.

I've written a test that demonstrates the bug, and you can find the referenced example CSV files [here](https://github.com/uniVocity/univocity-parsers/files/3527507/ExampleCSVs.zip).

```
import static org.assertj.core.api.Assertions.assertThat;

import org.apache.commons.lang3.StringUtils;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;

import com.univocity.parsers.common.ParsingContext;
import com.univocity.parsers.common.ResultIterator;
import com.univocity.parsers.common.record.Record;
import com.univocity.parsers.csv.CsvParser;
import com.univocity.parsers.csv.CsvParserSettings;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;

public class CSVParsingTest {

    CsvParser parser = new CsvParser(buildSettings());

    @Test
    @DisplayName("Demonstrate behavior is correct when no duplicates in headers")
    public void noDuplicates() {
        ResultIterator<Record, ParsingContext> iterator =
                getParsedIteratorForResource("NoDuplicates.csv");
        Record row = iterator.next();
        Map<String, String> parsedRow = row.fillFieldMap(new HashMap<>());
        assertThat(parsedRow)
                .hasSize(3)
                .containsEntry("notduplicate_1", "valueForFirst")
                .containsEntry("notduplicate_2", "valueForSecond")
                .containsEntry("notduplicate_3", "valueForThird");
    }

    @Test
    @DisplayName("Demonstrate behavior is correct when duplicates in headers, but the duplicate is not at the end")
    public void duplicatesNotAtEnd() {
        ResultIterator<Record, ParsingContext> iterator =
                getParsedIteratorForResource("DuplicatesNotAtEnd.csv");
        Record row = iterator.next();
        Map<String, String> parsedRow = row.fillFieldMap(new HashMap<>());
        assertThat(parsedRow)
                .hasSize(2)
                .hasEntrySatisfying("duplicate",
                        // could end up having either value depending on order found
                        value -> StringUtils.equalsAny("valueForFirst", "valueForSecond"))
                .containsEntry("notduplicate", "valueForThird");
    }

    @Test
    @DisplayName("Demonstrate behavior is incorrect when duplicates in headers and one is at the end")
    public void duplicatesAtEnd() {
        ResultIterator<Record, ParsingContext> iterator =
                getParsedIteratorForResource("DuplicateAtEnd.csv");
        Record row = iterator.next();
        Map<String, String> parsedRow = row.fillFieldMap(new HashMap<>());
        assertThat(parsedRow)
                .hasSize(3)
                .containsEntry("duplicate", "valueForFirst")
                .containsEntry("notduplicate", "valueForSecond")
                .containsEntry("duplicate\r", "valueForThird"); // carriage return kept
    }

    private ResultIterator<Record, ParsingContext> getParsedIteratorForResource(
            String classPathResource) {
        try {
            InputStream resource = new ClassPathResource(classPathResource).getInputStream();
            return parser.iterateRecords(
                    new InputStreamReader(resource,
                            StandardCharsets.UTF_8))
                    .iterator();
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    private CsvParserSettings buildSettings() {
        CsvParserSettings settings = new CsvParserSettings();
        settings.setHeaderExtractionEnabled(true);
        return settings;
    }
}

```

Thanks!

**Comment by jbax** [comment] 2019-11-26 03:29
Thanks for the great unit test. Unfortunately I'm unable to reproduce the error here. I've committed the unit test I built [here](https://github.com/uniVocity/univocity-parsers/blob/c1fce868eaea94acf1b01de5b52baf1ae78cac4b/src/test/java/com/univocity/parsers/issues/github/Github_349.java) and there is no key with a carriage return kept in test method `duplicatesAtEnd`.

To me it looks like you parsed a file that uses `\r\n` as line separator, but the parser ran with line separator set to `\n` AND `settings.trimValues(false);` - in which case the result you got would be valid.

I'm closing the issue but if you think there's a problem still please reopen with a self contained unit test that reproduces the error without depending on external files like the one I created.

Thank you

**Closed by jbax** 2019-11-26 03:29 UTC
Labels: bug
