### ISSUE TITLE
Ability to tell parser to use an "add" method instead of a "set"

### ISSUE THREAD

**Issue by NateAtBV** [uniVocity/univocity-parsers#160] opened 2017-05-26 11:37 UTC
Many of my classes have Collections of what would be considered Nested objects.  I would like to tell the parser to use the class's "add" method instead of the "set" method when it parses a Nested field.

**Comment by jbax** [comment] 2017-05-26 14:02
Duplicate of https://github.com/uniVocity/univocity-parsers/issues/139. Would you mind sharing your idea of how would you configure the annotations to populate your collection?

**Comment by NateAtBV** [comment] 2017-05-26 14:52
Sure.  I love the quick responses, btw.

Maybe something like this:
```
@Nested(method = "add")
List<MyObject> myObjects;
```
Or even

```
@Nested(method="addMyObject")
List<MyObject> myObjects;
```

So, instead of looking for a "setXXX" method to call, the parser calls "addXXX".

Or maybe the parser could detect that myObjects is a Collection and automatically look for an "addMyObject" method instead of "setMyObjects"?

To be clear: the use case is to only add _one_ instance of MyObject to the list.  I'm not asking for the parser to grab multiple instances of MyObject from the csv.  I would make that separate request.

**Comment by jbax** [comment] 2017-05-26 15:06
There's no need to provide a method name for it to add stuff to a collection, but it's nice to have. I believe the library can easily be modified to create a new instance of your collection (if it is null), and add elements to it. I'll try to make that work when the time allows.

**Comment by jbax** [comment] 2017-07-24 09:37
I've implemented support for adding annotations directly to methods. Now you can put a `Nested` annotation to any method that takes a single parameter. You can even populate a list with multiple objects now. Example using the `Car` with `Wheels`:

```
    public static class Car {
		List<Wheel> wheels = new ArrayList<Wheel>();

		@Nested(headerTransformer = NameTransformer.class, args = "frontLeftWheel")
		private void setWheel1(Wheel wheel) {
			wheels.add(wheel);
		}

		@Nested(headerTransformer = NameTransformer.class, args = "frontRightWheel")
		private void setWheel2(Wheel wheel) {
			wheels.add(wheel);
		}

		@Nested(headerTransformer = NameTransformer.class, args = "rearLeftWheel")
		private void setWheel3(Wheel wheel) {
			wheels.add(wheel);
		}

		@Nested(headerTransformer = NameTransformer.class, args = "rearRightWheel")
		private void setWheel4(Wheel wheel) {
			wheels.add(wheel);
		}
	}
```

Test code:

```
    String input = "frontLeftWheelBrand,frontLeftWheelMiles,frontRightWheelBrand,frontRightWheelMiles,rearLeftWheelBrand,rearLeftWheelMiles,rearRightWheelBrand,rearRightWheelMiles\n" +
				"b,2,b,4,b,6,v,3\n" +
				"c,1,c,3,c,1,z,9\n";

		CsvParserSettings settings = new CsvParserSettings();
		settings.getFormat().setLineSeparator("\n");

		List<Car> cars = new CsvRoutines(settings).parseAll(Car.class, new StringReader(input));
```

You can now also declare `Parsed` methods and add `Strings` to a `List`. Hope this helps. I'm releasing the 2.5.0 version today.

Thank you for using our parsers!

**Closed by jbax** 2017-07-24 09:37 UTC
Labels: enhancement
